# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sFDl6H3XR-GhHQJq8aPnA_7qSJ7nNaqB
"""

"""
Streamlit chat interface for the Amazon multimodal RAG assistant.
Imports all pipeline logic from rag_utils.py — this file only handles
UI rendering, resource caching, and session state.
"""

import uuid
import streamlit as st
from PIL import Image

from rag_utils import (
    load_clip,
    load_reranker,
    load_chroma_collection,
    load_llm,
    load_guardrails,
    run_rag_query,
    reset_session_history,
)

st.set_page_config(page_title="Amazon Product Assistant", page_icon="🛒")

"""## Cached Resource Loaders"""

# @st.cache_resource ensures each of these loads ONCE per server process,
# not once per user message. Without this, every chat message would
# reload CLIP, the reranker, and the LLM endpoint from scratch.

@st.cache_resource
def get_clip():
    return load_clip()

@st.cache_resource
def get_reranker():
    return load_reranker()

@st.cache_resource
def get_collection():
    return load_chroma_collection()

@st.cache_resource
def get_llm():
    return load_llm(hf_token=st.secrets["HF_TOKEN"])

@st.cache_resource
def get_guardrails():
    return load_guardrails()


# Load everything once
clip_model, clip_processor, device = get_clip()
reranker = get_reranker()
collection = get_collection()
llm = get_llm()
analyzer, anonymizer = get_guardrails()

"""## Session State"""

# Each browser tab gets its own session_id, so chat memory doesn't bleed between users.

if "session_id" not in st.session_state:
    st.session_state.session_id = str(uuid.uuid4())

if "messages" not in st.session_state:
    st.session_state.messages = []  # for rendering the chat log in the UI

"""## Sidebar"""

with st.sidebar:
    st.title("🛒 Amazon Product Assistant")
    st.caption(f"Products indexed: {collection.count()}")
    if st.button("Clear conversation"):
        st.session_state.messages = []
        reset_session_history(st.session_state.session_id)
        st.rerun()

    uploaded_image = st.file_uploader(
        "Upload a product photo (optional)", type=["jpg", "jpeg", "png"]
    )


query_image = None
if uploaded_image is not None:
    query_image = Image.open(uploaded_image).convert("RGB")
    st.sidebar.image(query_image, caption="Query image", use_column_width=True)

"""## Redner Chat History"""

for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.write(msg["content"])
        if msg.get("sources"):
            cols = st.columns(min(len(msg["sources"]), 4))
            for col, src in zip(cols, msg["sources"]):
                col.image(src, use_column_width=True)

"""## Chat Input"""

prompt = st.chat_input("Ask about a product...")

if prompt:
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.write(prompt)

    with st.chat_message("assistant"):
        with st.spinner("Searching products..."):
            result = run_rag_query(
                question=prompt,
                llm=llm,
                collection=collection,
                clip_model=clip_model,
                clip_processor=clip_processor,
                device=device,
                reranker=reranker,
                analyzer=analyzer,
                anonymizer=anonymizer,
                session_id=st.session_state.session_id,
                query_image=query_image,
            )

        st.write(result["answer"])

        if result["warning"]:
            st.warning(result["warning"])

        if result["sources"]:
            cols = st.columns(min(len(result["sources"]), 4))
            for col, src in zip(cols, result["sources"]):
                col.image(src, use_column_width=True)

        st.caption(f"Grounding score: {result['ground_score']}")

    st.session_state.messages.append({
        "role": "assistant",
        "content": result["answer"],
        "sources": result["sources"],
    })