# -*- coding: utf-8 -*-
"""rag_utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nJ-ynJELuUtJzHfCGwevh3zxh6Fj3eng
"""

"""
Multimodal RAG pipeline for Amazon product Q&A.
No Colab or Streamlit dependencies — safe to import from anywhere.
"""

import numpy as np
import torch
import chromadb
import requests
from io import BytesIO
from PIL import Image

from transformers import CLIPModel, CLIPProcessor
from sentence_transformers import CrossEncoder
from presidio_analyzer import AnalyzerEngine
from presidio_anonymizer import AnonymizerEngine

from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.runnables.history import RunnableWithMessageHistory
from langchain_core.chat_history import BaseChatMessageHistory
from langchain_community.chat_message_histories import ChatMessageHistory
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough
from langchain_huggingface import HuggingFaceEndpoint, ChatHuggingFace

"""## Configuration"""

CHROMA_PATH = "amazon_chroma_db"
COLLECTION_NAME = "amazon_products"
CLIP_MODEL_NAME = "openai/clip-vit-base-patch32"
RERANKER_MODEL_NAME = "cross-encoder/ms-marco-MiniLM-L-6-v2"
LLM_REPO_ID = "meta-llama/Meta-Llama-3-8B-Instruct"
BLOCKED_TOPICS = ["politics", "religion", "violence", "illegal", "drugs", "hate"]

"""## Resource Loaders (GPU/CPU)"""

def load_clip():
    device = "cuda" if torch.cuda.is_available() else "cpu"
    model = CLIPModel.from_pretrained(CLIP_MODEL_NAME).to(device)
    processor = CLIPProcessor.from_pretrained(CLIP_MODEL_NAME)
    model.eval()
    return model, processor, device


def load_reranker():
    return CrossEncoder(RERANKER_MODEL_NAME)


def load_chroma_collection(path: str = CHROMA_PATH, name: str = COLLECTION_NAME):
    client = chromadb.PersistentClient(path=path)
    return client.get_collection(name)


def load_llm(hf_token: str):
    endpoint = HuggingFaceEndpoint(
        repo_id=LLM_REPO_ID,
        huggingfacehub_api_token=hf_token,
        task="text-generation",
        max_new_tokens=300,
        temperature=0.2,
        do_sample=True,
    )
    return ChatHuggingFace(llm=endpoint)


def load_guardrails():
    analyzer = AnalyzerEngine()
    anonymizer = AnonymizerEngine()
    return analyzer, anonymizer

"""## Prompt"""

RAG_PROMPT = ChatPromptTemplate.from_messages([
    ("system", """You are a helpful product assistant for an e-commerce platform.
Answer customer questions about products using ONLY the provided context.

CRITICAL Guidelines:
- Answer DIRECTLY and SPECIFICALLY — lead with the answer in your first sentence.
- Use ONLY the provided product context — never fabricate specs, prices, or features.
- Keep answers focused and concise — 2 to 4 sentences.
- For image questions, describe the product and its key features.
- If the context does not contain the answer, say:
  "I don't have that information. Please visit the official product page or be more specific."
- Be concise, professional, and friendly.

Context:
{context}"""),
    MessagesPlaceholder(variable_name="chat_history"),
    ("human", "{input}"),
])

"""## Embeddings"""

def get_text_embedding(clip_model, clip_processor, device, text: str) -> list[float]:
    inputs = clip_processor(text=[text], return_tensors="pt", padding=True,
                             truncation=True, max_length=77).to(device)
    with torch.no_grad():
        raw = clip_model.get_text_features(**inputs)
        emb = raw if isinstance(raw, torch.Tensor) else raw.pooler_output
        emb = emb / emb.norm(dim=-1, keepdim=True)
    return emb.cpu().numpy()[0].tolist()


def get_image_embedding(clip_model, clip_processor, device, image: Image.Image) -> list[float]:
    inputs = clip_processor(images=image, return_tensors="pt").to(device)
    with torch.no_grad():
        raw = clip_model.get_image_features(**inputs)
        emb = raw if isinstance(raw, torch.Tensor) else raw.pooler_output
        emb = emb / emb.norm(dim=-1, keepdim=True)
    return emb.cpu().numpy()[0].tolist()


def load_image_from_url(url: str) -> Image.Image | None:
    try:
        resp = requests.get(url, timeout=10, headers={"User-Agent": "Mozilla/5.0"})
        resp.raise_for_status()
        return Image.open(BytesIO(resp.content)).convert("RGB")
    except Exception:
        return None

"""## Retrieval"""

def retrieve_products(
    collection,
    clip_model, clip_processor, device,
    reranker,
    query_text: str = None,
    query_image: Image.Image = None,
    top_k: int = 5,
) -> list[dict]:
    n_candidates = min(20, collection.count())
    if n_candidates == 0:
        return []

    if query_text and query_image:
        text_emb = get_text_embedding(clip_model, clip_processor, device, query_text)
        image_emb = get_image_embedding(clip_model, clip_processor, device, query_image)
        query_emb = np.mean([text_emb, image_emb], axis=0).tolist()
    elif query_image:
        query_emb = get_image_embedding(clip_model, clip_processor, device, query_image)
    else:
        query_emb = get_text_embedding(clip_model, clip_processor, device, query_text)

    results = collection.query(
        query_embeddings=[query_emb],
        n_results=n_candidates,
        include=["documents", "metadatas", "distances"],
    )

    candidates = list(zip(results["documents"][0], results["metadatas"][0], results["distances"][0]))

    if query_text and candidates:
        pairs = [[query_text, doc] for doc, _, _ in candidates]
        scores = reranker.predict(pairs)
        ranked = sorted(zip(scores, candidates), key=lambda x: x[0], reverse=True)
        candidates = [c for _, c in ranked]

    return [
        {"text": doc, "metadata": meta, "similarity": round(1 - dist, 4)}
        for doc, meta, dist in candidates[:top_k]
    ]

"""## Guardrails"""

def redact_pii(analyzer, anonymizer, text: str) -> str:
    results = analyzer.analyze(text=text, language="en")
    if not results:
        return text
    return anonymizer.anonymize(text=text, analyzer_results=results).text


def is_appropriate(query: str) -> bool:
    return not any(t in query.lower() for t in BLOCKED_TOPICS)


def check_hallucination(answer: str, contexts: list[str]) -> dict:
    context = " ".join(contexts).lower()
    words = answer.lower().split()
    phrases = [" ".join(words[i:i + 3]) for i in range(len(words) - 2)]
    if not phrases:
        return {"grounded": True, "score": 1.0, "warning": None}
    score = round(sum(1 for p in phrases if p in context) / len(phrases), 2)
    warning = "⚠ Answer may contain info not found in source documents." if score < 0.3 else None
    return {"grounded": score >= 0.3, "score": score, "warning": warning}

"""## Session History"""

_history_store: dict[str, BaseChatMessageHistory] = {}

def get_session_history(session_id: str) -> BaseChatMessageHistory:
    if session_id not in _history_store:
        _history_store[session_id] = ChatMessageHistory()
    return _history_store[session_id]

def reset_session_history(session_id: str) -> None:
    _history_store[session_id] = ChatMessageHistory()

"""## Main RAG Query"""

def run_rag_query(
    question: str,
    llm,
    collection,
    clip_model, clip_processor, device,
    reranker,
    analyzer, anonymizer,
    session_id: str,
    query_image: Image.Image = None,
    precomputed_products: list = None,
) -> dict:
    clean_question = redact_pii(analyzer, anonymizer, question).strip() if question else ""

    if clean_question and not is_appropriate(clean_question):
        return {
            "question": question, "answer": "I can't respond to that type of question.",
            "contexts": [], "products": [], "sources": [],
            "grounded": None, "ground_score": None, "warning": None,
        }

    products = precomputed_products if precomputed_products is not None else retrieve_products(
        collection, clip_model, clip_processor, device, reranker,
        query_text=clean_question or None, query_image=query_image, top_k=5,
    )

    context = "\n\n".join(f"[Product {i+1}]\n{p['text']}" for i, p in enumerate(products))

    if query_image and clean_question:
        input_text = f"{clean_question} [User also uploaded a product image]"
    elif query_image:
        input_text = "Can you identify this product and describe its features and usage?"
    else:
        input_text = clean_question

    chain = (
        RunnablePassthrough.assign(context=lambda _: context)
        | RAG_PROMPT
        | llm
        | StrOutputParser()
    )

    qa_chain_run = RunnableWithMessageHistory(
        chain, get_session_history,
        input_messages_key="input", history_messages_key="chat_history",
    )

    answer = qa_chain_run.invoke(
        {"input": input_text},
        config={"configurable": {"session_id": session_id}},
    )

    contexts = [p["text"] for p in products]
    hallucination = check_hallucination(answer, contexts)
    sources = [p["metadata"].get("image_url", "") for p in products if p["metadata"].get("image_url")]

    return {
        "question": question, "answer": answer, "contexts": contexts,
        "products": products, "sources": sources,
        "grounded": hallucination["grounded"], "ground_score": hallucination["score"],
        "warning": hallucination["warning"],
    }